version: '3'
services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/postgres/volumes:/var/lib/postgres
      - ./docker/postgres/:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"