spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pebble
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: false
server:
  compression:
    enabled: true
  use-forward-headers: true